# Generated by Django 5.1.6 on 2025-03-03 05:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_sale_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='submission_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
